=== RazaToosy/CsvMapper/CsvMapper.Infrastructure/BaseSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Mapping">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Map" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Source">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:byte" name="ConnectTo" use="optional"/>
                      <xs:attribute type="xs:byte" name="SourceId" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="Destination">
                <xs:annotation>
                  <xs:documentation>If no source then doesn't look in souce csv. Ie need to generate based on Action aloneIf no source then doesn't look in souce csv. Ie need to generate based on Action alone</xs:documentation>
                </xs:annotation>
              </xs:element>
              <xs:element name="Process">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Command" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:string" name="Where" minOccurs="0"/>
                          <xs:element type="xs:string" name="Make" minOccurs="0">
                            <xs:annotation>
                              <xs:documentation>No Source so this will be blank. To add TES to this column</xs:documentation>
                            </xs:annotation>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="action" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="datatype" use="optional"/>
            <xs:attribute type="xs:byte" name="id" use="optional"/>
            <xs:attribute type="xs:byte" name="if" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RazaToosy/CsvMapper/CsvMapper.Infrastructure/2 year old patient list immunisation targets.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Mapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:BaseSchema BaseSchema.xsd">
  <Map datatype ="String" id="1">
    <Source ConnectTo="0" SourceId="1"><![CDATA[Full Name]]></Source>
    <Destination/> <!--If Blank then ignored in the transformation-->
    <Process/>
  </Map>
  <Map datatype ="String" id="2">
    <Source ConnectTo="0" SourceId="2"><![CDATA[Date of Birth]]></Source>
    <Destination/>
    <Process/>
  </Map>
  <Map datatype ="String" id="3">
    <Source ConnectTo="1" SourceId="4"><![CDATA[Usual GP's Full Name]]></Source>
    <Destination><![CDATA[GP_CODE]]></Destination>
    <Process>
      <Command action ="Load">
        <Where>GPCodes.csv</Where>
      </Command>
    </Process>
  </Map>
  <Map datatype ="DateTime" id="4">
    <Source ConnectTo="0" SourceId="0"/> <!--If no source then doesn't look in souce csv. Ie need to generate based on Action alone-->
    <Destination><![CDATA[LIST_DATE]]></Destination>
    <Process>
      <Command action="QuarterStart"/>
    </Process>
  </Map>
  <Map  datatype ="String" id="5">
    <Source ConnectTo="0" SourceId="0"/>
    <!--If no source then doesn't look in souce csv. Ie need to generate based on Action alone-->
    <Destination><![CDATA[DATASOURCE]]></Destination>
    <Process>
      <Command action="RegexAction">
        <Where/> <!--No Source so this will be blank. To add TES to this column-->
        <Make><![CDATA[TES]]></Make>
      </Command>
    </Process>
  </Map>
  <Map datatype ="String" id="6">
    <Source ConnectTo="4" SourceId="3"><![CDATA[NHS Number]]></Source>
    <Destination><![CDATA[NHS_Number]]></Destination>
    <Process>
      <Command action="Removespaces"/>
    </Process>
  </Map>
  <Map  datatype ="DateTime" id="7">
    <Source ConnectTo="5" SourceId="5"><![CDATA[Date]]></Source>
    <Destination><![CDATA[MMR_DATE]]></Destination>
    <Process>
      <Command action="SimpleMapping"/>
    </Process>
  </Map>
  <Map  datatype ="String" id="8">
    <Source ConnectTo="6" SourceId="6"><![CDATA[As GMS]]></Source>
    <Destination><![CDATA[MMR_UNDER_GMS]]></Destination>
    <Process>
      <Command action="RegexAction">
        <Where><![CDATA[^True$]]></Where>
        <Make><![CDATA[Y]]></Make>
      </Command>
      <Command action="RegexAction">
        <Where><![CDATA[^False$]]></Where>
        <Make><![CDATA[N]]></Make>
      </Command>
    </Process>
  </Map>
  <Map datatype ="DateTime" id="9">
    <Source ConnectTo="7" SourceId="7"><![CDATA[Date]]></Source>
    <Destination><![CDATA[FIVE_IN_ONE_DATE]]></Destination>
    <Process>
      <Command action="SimpleMapping"/>
    </Process>
  </Map>
  <Map datatype ="String" id="10">
    <Source ConnectTo="8" SourceId="8"><![CDATA[As GMS]]></Source>
    <Destination><![CDATA[FIVE_IN_ONE_UNDER_GMS]]></Destination>
    <Process>
      <Command action="RegexAction">
        <Where><![CDATA[^True$]]></Where>
        <Make><![CDATA[Y]]></Make>
      </Command>
      <Command action="RegexAction">
        <Where><![CDATA[^False$]]></Where>
        <Make><![CDATA[N]]></Make>
      </Command>
    </Process>
  </Map>
  <Map datatype ="DateTime" id="11">
    <Source ConnectTo="9" SourceId="9"><![CDATA[Date]]></Source>
    <Destination><![CDATA[MENC_DATE]]></Destination>
    <Process>
      <Command action="SimpleMapping"/>
    </Process>
  </Map>
  <Map datatype ="String" id="12">
    <Source ConnectTo="10" SourceId="10"><![CDATA[As GMS]]></Source>
    <Destination><![CDATA[MENC_UNDER_GMS]]></Destination>
    <Process>
      <Command action="RegexAction">
        <Where><![CDATA[^True$]]></Where>
        <Make><![CDATA[Y]]></Make>
      </Command>
      <Command action="RegexAction">
        <Where><![CDATA[^False$]]></Where>
        <Make><![CDATA[N]]></Make>
      </Command>
    </Process>
  </Map>
</Mapping>
